// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARrrLmHBsass-6mDryjzKsOEiFbSpDwsc',
    appId: '1:970325205793:web:f17f175a4dcf0cbf6c1460',
    messagingSenderId: '970325205793',
    projectId: 'sawa-scanner',
    authDomain: 'sawa-scanner.firebaseapp.com',
    storageBucket: 'sawa-scanner.firebasestorage.app',
    measurementId: 'G-583ZKNPBZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcgWT0Cy8cOjPyVjODUPu1sZMtS7ybxE',
    appId: '1:970325205793:android:43415da30c66b2a76c1460',
    messagingSenderId: '970325205793',
    projectId: 'sawa-scanner',
    storageBucket: 'sawa-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXgBBRfuvHZTTzsxL7FgnoxCR6OB3wwtk',
    appId: '1:970325205793:ios:82f4a11460bed7c86c1460',
    messagingSenderId: '970325205793',
    projectId: 'sawa-scanner',
    storageBucket: 'sawa-scanner.firebasestorage.app',
    iosBundleId: 'com.ahmedmadani.sawascanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARrrLmHBsass-6mDryjzKsOEiFbSpDwsc',
    appId: '1:970325205793:web:2db70395eb55e9f06c1460',
    messagingSenderId: '970325205793',
    projectId: 'sawa-scanner',
    authDomain: 'sawa-scanner.firebaseapp.com',
    storageBucket: 'sawa-scanner.firebasestorage.app',
    measurementId: 'G-J8CEMW21ZS',
  );
}
