import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1779346810846 implements MigrationInterface {
    name = 'Migration1779346810846'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nutrition_fact" DROP CONSTRAINT "FK_nutrition_product"`);
        await queryRunner.query(`ALTER TABLE "ingredient" DROP CONSTRAINT "FK_ingredient_product"`);
        await queryRunner.query(`ALTER TABLE "store" DROP CONSTRAINT "FK_store_merchant"`);
        await queryRunner.query(`ALTER TABLE "product_price" DROP CONSTRAINT "FK_price_product"`);
        await queryRunner.query(`ALTER TABLE "product_price" DROP CONSTRAINT "FK_price_merchant"`);
        await queryRunner.query(`ALTER TABLE "product_price" DROP CONSTRAINT "FK_price_store"`);
        await queryRunner.query(`ALTER TABLE "product_image" DROP CONSTRAINT "FK_image_product"`);
        await queryRunner.query(`ALTER TABLE "product_allergen" DROP CONSTRAINT "FK_product_allergen_product"`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" DROP CONSTRAINT "FK_pan_product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingredient_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_price_scraped_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_price_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_price_merchant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_price_store_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_allergen_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_gtin"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_brand_normalized"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_brand_normalized_weight"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_gtin_unique_nonnull"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_gtin_prefix"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sfda_prohibited_ingredients_e_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_report_gtin"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pml_loser_gtin"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pml_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pml_winner_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pan_product_id"`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" DROP CONSTRAINT "UQ_pan_product_name"`);
        await queryRunner.query(`ALTER TABLE "product_image" ADD "image_hash" character varying(16)`);
        await queryRunner.query(`ALTER TABLE "merchant" ALTER COLUMN "name_en" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "store" ALTER COLUMN "last_seen_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "UQ_85bd0246bfcc1b71cfff40f29b0" UNIQUE ("gtin")`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "UQ_12084be5747159af8fd8c270f3e" UNIQUE ("hs_product_id")`);
        await queryRunner.query(`ALTER TABLE "sfda_prohibited_ingredients" DROP COLUMN "sfda_status"`);
        await queryRunner.query(`CREATE TYPE "public"."sfda_prohibited_ingredients_sfda_status_enum" AS ENUM('prohibited', 'restricted')`);
        await queryRunner.query(`ALTER TABLE "sfda_prohibited_ingredients" ADD "sfda_status" "public"."sfda_prohibited_ingredients_sfda_status_enum" NOT NULL DEFAULT 'prohibited'`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_11f79befda64e8f2f2aad0b94d" ON "ingredient" ("product_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1b476f52f6e3d052b8b2f5c877" ON "merchant" ("name_en") `);
        await queryRunner.query(`CREATE INDEX "IDX_14932618332f38685d17d2c899" ON "product_price" ("scraped_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0da08b762f53700e4f8760a9b5" ON "product_price" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d33bccceda0c90a1c99803ddd" ON "product_price" ("merchant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_809dc8247f3d16fdf3ecc728e5" ON "product_price" ("store_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4a06adb570ae7190d2adde45d" ON "product_image" ("image_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_product_image_product_url" ON "product_image" ("product_id", "url") `);
        await queryRunner.query(`CREATE INDEX "IDX_19c0a64954a39d1f9107c2e84c" ON "product_allergen" ("product_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee613bfcaf92fb1ab7c5990f10" ON "product" ("gtin") WHERE "gtin" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_7d9f8fd96b2136801ed49339a0" ON "product" ("brand_normalized") `);
        await queryRunner.query(`CREATE INDEX "IDX_c594429b65995567176d24686d" ON "product" ("gtin_prefix") `);
        await queryRunner.query(`CREATE INDEX "IDX_1be83bcc25d0727f8fe1f637d4" ON "product" ("brand_normalized", "net_weight_value", "net_unit") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f116fbeb31540daafd1d72812" ON "sfda_prohibited_ingredients" ("e_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a8cc692b26bdcc70ba1ac8bd5" ON "product_report" ("gtin") `);
        await queryRunner.query(`CREATE INDEX "IDX_81d196f495d2ff2e133ad0df02" ON "product_merge_log" ("winner_product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cea2eeb183a816791a4b2775f" ON "product_merge_log" ("loser_product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_12b17215b787f23e3b7c630c49" ON "product_merge_log" ("loser_gtin") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d184a89a690a6cd7829cfc3b0" ON "product_merge_log" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d6ea19eedc529d54c05931848" ON "product_alternative_name" ("product_id") `);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" ADD CONSTRAINT "UQ_e1b9323e332961f7ec56015d7b2" UNIQUE ("product_id", "name")`);
        await queryRunner.query(`ALTER TABLE "nutrition_fact" ADD CONSTRAINT "FK_edc5571b96b04190a67673413d4" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient" ADD CONSTRAINT "FK_11f79befda64e8f2f2aad0b94db" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store" ADD CONSTRAINT "FK_86ddc4a94ec82e28bf66d6af7fe" FOREIGN KEY ("merchant_id") REFERENCES "merchant"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_price" ADD CONSTRAINT "FK_0da08b762f53700e4f8760a9b5c" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_price" ADD CONSTRAINT "FK_9d33bccceda0c90a1c99803dddc" FOREIGN KEY ("merchant_id") REFERENCES "merchant"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_price" ADD CONSTRAINT "FK_809dc8247f3d16fdf3ecc728e52" FOREIGN KEY ("store_id") REFERENCES "store"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image" ADD CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_allergen" ADD CONSTRAINT "FK_19c0a64954a39d1f9107c2e84cf" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" ADD CONSTRAINT "FK_2d6ea19eedc529d54c05931848a" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_alternative_name" DROP CONSTRAINT "FK_2d6ea19eedc529d54c05931848a"`);
        await queryRunner.query(`ALTER TABLE "product_allergen" DROP CONSTRAINT "FK_19c0a64954a39d1f9107c2e84cf"`);
        await queryRunner.query(`ALTER TABLE "product_image" DROP CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3"`);
        await queryRunner.query(`ALTER TABLE "product_price" DROP CONSTRAINT "FK_809dc8247f3d16fdf3ecc728e52"`);
        await queryRunner.query(`ALTER TABLE "product_price" DROP CONSTRAINT "FK_9d33bccceda0c90a1c99803dddc"`);
        await queryRunner.query(`ALTER TABLE "product_price" DROP CONSTRAINT "FK_0da08b762f53700e4f8760a9b5c"`);
        await queryRunner.query(`ALTER TABLE "store" DROP CONSTRAINT "FK_86ddc4a94ec82e28bf66d6af7fe"`);
        await queryRunner.query(`ALTER TABLE "ingredient" DROP CONSTRAINT "FK_11f79befda64e8f2f2aad0b94db"`);
        await queryRunner.query(`ALTER TABLE "nutrition_fact" DROP CONSTRAINT "FK_edc5571b96b04190a67673413d4"`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" DROP CONSTRAINT "UQ_e1b9323e332961f7ec56015d7b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d6ea19eedc529d54c05931848"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d184a89a690a6cd7829cfc3b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12b17215b787f23e3b7c630c49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cea2eeb183a816791a4b2775f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81d196f495d2ff2e133ad0df02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a8cc692b26bdcc70ba1ac8bd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f116fbeb31540daafd1d72812"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1be83bcc25d0727f8fe1f637d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c594429b65995567176d24686d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d9f8fd96b2136801ed49339a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee613bfcaf92fb1ab7c5990f10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19c0a64954a39d1f9107c2e84c"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_product_image_product_url"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4a06adb570ae7190d2adde45d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_809dc8247f3d16fdf3ecc728e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d33bccceda0c90a1c99803ddd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0da08b762f53700e4f8760a9b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14932618332f38685d17d2c899"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b476f52f6e3d052b8b2f5c877"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11f79befda64e8f2f2aad0b94d"`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sfda_prohibited_ingredients" DROP COLUMN "sfda_status"`);
        await queryRunner.query(`DROP TYPE "public"."sfda_prohibited_ingredients_sfda_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sfda_prohibited_ingredients" ADD "sfda_status" character varying NOT NULL DEFAULT 'prohibited'`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "UQ_12084be5747159af8fd8c270f3e"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "UQ_85bd0246bfcc1b71cfff40f29b0"`);
        await queryRunner.query(`ALTER TABLE "store" ALTER COLUMN "last_seen_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant" ALTER COLUMN "name_en" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_image" DROP COLUMN "image_hash"`);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" ADD CONSTRAINT "UQ_pan_product_name" UNIQUE ("name", "product_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_pan_product_id" ON "product_alternative_name" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_pml_winner_product_id" ON "product_merge_log" ("winner_product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_pml_created_at" ON "product_merge_log" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_pml_loser_gtin" ON "product_merge_log" ("loser_gtin") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_report_gtin" ON "product_report" ("gtin") `);
        await queryRunner.query(`CREATE INDEX "IDX_sfda_prohibited_ingredients_e_number" ON "sfda_prohibited_ingredients" ("e_number") `);
        await queryRunner.query(`CREATE INDEX "idx_product_gtin_prefix" ON "product" ("gtin_prefix") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_product_gtin_unique_nonnull" ON "product" ("gtin") WHERE (gtin IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_product_brand_normalized_weight" ON "product" ("brand_normalized", "net_unit", "net_weight_value") `);
        await queryRunner.query(`CREATE INDEX "idx_product_brand_normalized" ON "product" ("brand_normalized") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_product_gtin" ON "product" ("gtin") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_allergen_product_id" ON "product_allergen" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_price_store_id" ON "product_price" ("store_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_price_merchant_id" ON "product_price" ("merchant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_price_product_id" ON "product_price" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_price_scraped_at" ON "product_price" ("scraped_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingredient_product_id" ON "ingredient" ("product_id") `);
        await queryRunner.query(`ALTER TABLE "product_alternative_name" ADD CONSTRAINT "FK_pan_product" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_allergen" ADD CONSTRAINT "FK_product_allergen_product" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image" ADD CONSTRAINT "FK_image_product" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_price" ADD CONSTRAINT "FK_price_store" FOREIGN KEY ("store_id") REFERENCES "store"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_price" ADD CONSTRAINT "FK_price_merchant" FOREIGN KEY ("merchant_id") REFERENCES "merchant"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_price" ADD CONSTRAINT "FK_price_product" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store" ADD CONSTRAINT "FK_store_merchant" FOREIGN KEY ("merchant_id") REFERENCES "merchant"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient" ADD CONSTRAINT "FK_ingredient_product" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition_fact" ADD CONSTRAINT "FK_nutrition_product" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
