export const DISTRICT_TRANSLATIONS: Record<string, string> = {
  'sahafah': 'الصحافة',
  'ghadir': 'الغدير',
  'al wisham': 'الوشام',
  'ghirnatah': 'غرناطة',
  'aqiq': 'العقيق',
  'al isdihar': 'الازدهار',
  'al rabwah': 'الربوة',
  'ash shifa': 'الشفا',
  'mikal': 'معكال',
  'mutamarat': 'المؤتمرات',
  'malaz': 'الملز',
  'imam muhammad ibn saud islamic university': 'جامعة الإمام محمد بن سعود الإسلامية',
  'alawali': 'العوالي',
  'salah ad din': 'صلاح الدين',
  'hada': 'الهدا',
  'uraija al gharbiyah': 'العريجاء الغربية',
  'king khalid airport': 'مطار الملك خالد',
  'al mohammadiyah': 'المحمدية',
  'al mishal': 'المشاعل',
  'al rawabi': 'الروابي',
  'utaiqah': 'عتيقة',
  'rafiah': 'الرفيعة',
  'malqa': 'الملقا',
  'al mathar ash shamali': 'المعذر الشمالي',
  'dhahrat al badiah': 'ظهرة البديعة',
  'al nada': 'الندى',
  'al morsalat': 'المرسلات',
  'narjis': 'النرجس',
  'an nakhil': 'النخيل',
  'east an nasim': 'النسيم الشرقي',
  'jabrah': 'جبرة',
  'al \'uraija': 'العريجاء',
  'namudhajiyah': 'النموذجية',
  'duraihmiyah': 'الدريهمية',
  'winter wonderland': 'ونتر وندرلاند',
  'oud': 'العود',
  'al yarmok': 'اليرموك',
  'al shomaisi': 'الشميسي',
  'king abdllah neighborhood': 'حي الملك عبد الله',
  'al arid': 'العارض',
  'king fahd neighborhood': 'حي الملك فهد',
  'skirinah': 'سكيرينة',
  'al rawdah': 'الروضة',
  'ulaishah': 'عليشة',
  'rabie': 'الربيع',
  'dar al baida': 'الدار البيضاء',
  'janadriyah': 'الجنادرية',
  'banban': 'بنبان',
  'king saud university': 'جامعة الملك سعود',
  'yamamah': 'اليمامة',
  'irqah': 'عرقة',
  'al falah': 'الفلاح',
  'yasmin': 'الياسمين',
  'al waha': 'الواحة',
  'al mughrizat': 'المغرزات',
  'hamra': 'الحمراء',
  'qurtubah': 'قرطبة',
  'ad dhubbat': 'الضباط',
  'ash shuhada': 'الشهداء',
  'al andalus': 'الأندلس',
  'al muruj': 'المروج',
  'dubiyah': 'دوبية',
  'al ta\'awun': 'التعاون',
  'al nafal': 'النفل',
  'qirawan': 'القيروان',
  'king faisal neighborhood': 'حي الملك فيصل',
  'ishbiliyah': 'إشبيلية',
  'king abdulaziz neighborhood': 'حي الملك عبد العزيز',
  'munsiyah': 'المؤنسية',
  'qadisiayh': 'القادسية',
  'salhiyah': 'الصالحية',
  'shubra': 'شبرا',
  'hateen': 'حطين',
  'al khaleej': 'الخليج',
  'princess nora bint abdul rahman university': 'جامعة الأميرة نورة بنت عبد الرحمن',
  'al wurud': 'الورود',
  'ar rihab': 'الرحاب',
  'al wadi': 'الوادي',
  'al quds': 'القدس',
  'faruq': 'الفاروق',
  'umm al hamam algarbi': 'أم الحمام الغربي',
  'ar rayyan': 'الريان',
  'maizlh': 'المعيزيلة',
  'al nuzhah': 'النزهة',
  'rahmaniyah': 'الرحمانية',
  'masiaf': 'المصيف',
  'an nasim al gharbi': 'النسيم الغربي',
  'manar': 'المنار',
  'khuzama': 'الخزامى',
  'sinaiyah': 'الصناعية',
  'umm al hamam ash sharqi': 'أم الحمام الشرقي',
  'alsharq': 'الشرق',
  'al safarat': 'السفارات',
  'saadah': 'السعادة',
  'al nahda': 'النهضة',
  'al wizarat': 'الوزارات',
  'safa': 'الصفا',
  'al sulaymanaya': 'السليمانية',
  'al futha': 'الفوطة',
  'al zahra': 'الزهراء',
  'jarir': 'جرير',
  'thulaim': 'ثليم',
  'faisaliyah': 'الفيصلية',
  'al olaya': 'العليا',
  'an nasiriyah': 'الناصرية',
  'rimayah': 'الرماية',
  'al mansourah': 'المنصورة',
  'al maather': 'المعذر',
  'al fakhiriyah': 'الفاخرية',
  'al morabaa': 'المربع',
  'al wusaita': 'الوسيطاء',
  'ghubairuh': 'غبيراء',
  'nur': 'النور',
  'as salam': 'السلام',
  'alqura': 'القرى',
  'dirah': 'الديرة',
  'sharafiyah': 'الشرفية',
  'faiha': 'الفيحاء',
  'al butaiha': 'البطحاء',
  'marqab': 'المرقب',
  'khaldiyah': 'الخالدية',
  'laban': 'لبن',
  'uraija al wusta': 'العريجاء الوسطى',
  'siyah': 'الصياح',
  'umm salim': 'أم سليم',
  'manfouhah al jadidah': 'منفوحة الجديدة',
  'as suwaidi al gharabi': 'السويدي الغربي',
  'al suwaidi': 'السويدي',
  'zahrah': 'الزهرة',
  'al badi\'ah': 'البديعة',
  'jazirah': 'الجزيرة',
  'namar': 'نمار',
  'manakh': 'مناخ',
  'al amal': 'العمل',
  'al iskan': 'الإسكان',
  'raid': 'الرائد',
  'al azizyah': 'العزيزية',
  'manfuhah': 'منفوحة',
  'dhahrat laban': 'ظهرة لبن',
  'as sulay': 'السلي',
  'al mahdiyah': 'المهدية',
  'al jaradiyah': 'الجرادية',
  'tuwaiq': 'طويق',
  'al hazm': 'الحزم',
  'sultanah': 'سلطانة',
  'ad difa': 'الدفاع',
  'al marwah': 'المروة',
  'al massani': 'المصانع',
  'rimal': 'الرمال',
  'dirab': 'ديراب',
  'uhud': 'أحد',
  'badr': 'بدر',
  'taybah': 'طيبة',
  'al jubaylah': 'الجبيلة',
  'ad diriyah': 'الدرعية',
  'misfat': 'مصفاة',
  'al moqbel palaces': 'قصور آل مقبل',
  'okaz': 'عكاظ',
  'al ghnamiah': 'الغنامية',
  'dahiat namar': 'ضاحية نمار',
  'arid': 'العارض',
  'mansoriah': 'المنصورية',
  'new industrial area': 'المدينة الصناعية الجديدة',
  'al uyaynah': 'العيينة'
};

export function translateDistrict(englishName: string | undefined): string | undefined {
  if (!englishName) return undefined;
  const key = englishName.trim().toLowerCase();
  return DISTRICT_TRANSLATIONS[key] || undefined;
}
